# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x2PIEo1J6LMF_bV2f7_7rkGtMLrJ9uL1
"""

import re
import streamlit as st
from utils.agent_utils import run_compliance_agent

st.set_page_config(
    page_title="AI Compliance Dashboard",
    page_icon="🛡️",
    layout="wide"
)


def extract_score(text):
    match = re.search(r"Overall Compliance Score:\s*([0-9]+)%", text)
    if match:
        return int(match.group(1))
    return None


def extract_section(text, section_name):
    pattern = rf"{section_name}:\s*(.*?)(?=\n[A-Z][A-Za-z\s\-]+:|\Z)"
    match = re.search(pattern, text, re.S)
    if match:
        return match.group(1).strip()
    return ""


def count_bullets(section_text):
    if not section_text:
        return 0
    lines = [line.strip() for line in section_text.splitlines() if line.strip()]
    return sum(1 for line in lines if line.startswith("-"))


def get_status(score):
    if score is None:
        return "Not Available"
    if score >= 80:
        return "High Compliance"
    if score >= 60:
        return "Moderate Compliance"
    return "Low Compliance"


def render_score_bar(score):
    if score is None:
        st.progress(0)
        return

    st.progress(score / 100)


st.markdown(
    """
    <style>
    .main-title {
        font-size: 34px;
        font-weight: 800;
        margin-bottom: 6px;
    }
    .sub-title {
        color: #6b7280;
        font-size: 16px;
        margin-bottom: 24px;
    }
    .card {
        background-color: #f8fafc;
        border: 1px solid #e5e7eb;
        border-radius: 18px;
        padding: 18px;
        margin-bottom: 16px;
    }
    .result-box {
        background-color: #ffffff;
        border: 1px solid #e5e7eb;
        border-radius: 18px;
        padding: 20px;
        box-shadow: 0 2px 10px rgba(0,0,0,0.04);
    }
    .small-note {
        color: #6b7280;
        font-size: 13px;
    }
    </style>
    """,
    unsafe_allow_html=True
)

# Header
st.markdown('<div class="main-title">🛡️ AI Internal Audit Compliance Dashboard</div>', unsafe_allow_html=True)
st.markdown(
    '<div class="sub-title">Compare a mother policy against an internal policy, retrieve relevant evidence, and generate a compliance assessment dashboard.</div>',
    unsafe_allow_html=True
)

# Workflow section
st.markdown("### Workflow")
wf1, wf2, wf3 = st.columns(3)

with wf1:
    st.info("**1. Upload Policies**\n\nUpload the mother policy and the internal policy in PDF format.")
with wf2:
    st.info("**2. Analyze Compliance**\n\nThe system extracts text, chunks content, retrieves relevant internal sections, and compares them.")
with wf3:
    st.info("**3. Review Dashboard**\n\nGet a compliance score, findings, recommendations, and retrieved evidence.")

st.markdown("---")

# Upload section
st.markdown("### Upload Policy Documents")
col1, col2 = st.columns(2)

with col1:
    st.markdown('<div class="card">', unsafe_allow_html=True)
    mother_file = st.file_uploader("Upload Mother Policy", type=["pdf"], key="mother_file")
    st.markdown('<div class="small-note">Reference framework, regulation, or parent policy.</div>', unsafe_allow_html=True)
    st.markdown("</div>", unsafe_allow_html=True)

with col2:
    st.markdown('<div class="card">', unsafe_allow_html=True)
    internal_file = st.file_uploader("Upload Internal Policy", type=["pdf"], key="internal_file")
    st.markdown('<div class="small-note">Internal policy that will be assessed against the mother policy.</div>', unsafe_allow_html=True)
    st.markdown("</div>", unsafe_allow_html=True)

# Advanced settings
with st.expander("Advanced Settings"):
    query = st.text_area(
        "Retrieval Query",
        value="data retention, incident response, compliance monitoring, governance roles, access control, policy requirements",
        help="This query guides the retrieval step to pull the most relevant internal policy chunks."
    )
    top_k = st.slider("Number of Retrieved Chunks", min_value=3, max_value=10, value=5)
    mother_max_chars = st.slider("Mother Policy Max Characters", min_value=4000, max_value=20000, value=12000, step=1000)
    internal_max_chars = st.slider("Internal Context Max Characters", min_value=4000, max_value=20000, value=12000, step=1000)

run_clicked = st.button("Run Compliance Analysis", use_container_width=True)

if run_clicked:
    if not mother_file or not internal_file:
        st.warning("Please upload both PDF files before running the analysis.")
    else:
        with st.spinner("Analyzing policies and building dashboard..."):
            try:
                result = run_compliance_agent(
                    mother_file=mother_file,
                    internal_file=internal_file,
                    query=query,
                    top_k=top_k,
                    mother_max_chars=mother_max_chars,
                    internal_max_chars=internal_max_chars
                )

                analysis_text = result["analysis_result"]

                score = extract_score(analysis_text)
                status = get_status(score)

                summary = extract_section(analysis_text, "Summary")
                compliant = extract_section(analysis_text, "Compliant Areas")
                partially_compliant = extract_section(analysis_text, "Partially Compliant Areas")
                non_compliant = extract_section(analysis_text, "Non-Compliant Areas")
                recommendations = extract_section(analysis_text, "Recommendations")

                compliant_count = count_bullets(compliant)
                partial_count = count_bullets(partially_compliant)
                non_compliant_count = count_bullets(non_compliant)
                recommendation_count = count_bullets(recommendations)

                processed = result["processed_data"]
                retrieved_chunks = result["retrieved_chunks"]

                st.markdown("---")
                st.markdown("## Executive Dashboard")

                # KPI Cards
                k1, k2, k3, k4 = st.columns(4)
                with k1:
                    st.metric("Compliance Score", f"{score}%" if score is not None else "N/A")
                with k2:
                    st.metric("Status", status)
                with k3:
                    st.metric("Non-Compliant Items", non_compliant_count)
                with k4:
                    st.metric("Retrieved Chunks", len(retrieved_chunks))

                st.markdown("### Compliance Score Overview")
                render_score_bar(score)

                c1, c2 = st.columns([1.2, 1])

                with c1:
                    st.markdown("### Summary")
                    st.markdown('<div class="result-box">', unsafe_allow_html=True)
                    st.markdown(summary if summary else "No summary available.")
                    st.markdown("</div>", unsafe_allow_html=True)

                with c2:
                    st.markdown("### Findings Overview")
                    st.markdown('<div class="result-box">', unsafe_allow_html=True)
                    st.write(f"Compliant Areas: **{compliant_count}**")
                    st.write(f"Partially Compliant Areas: **{partial_count}**")
                    st.write(f"Non-Compliant Areas: **{non_compliant_count}**")
                    st.write(f"Recommendations: **{recommendation_count}**")
                    st.markdown("</div>", unsafe_allow_html=True)

                st.markdown("## Detailed Findings")

                d1, d2 = st.columns(2)

                with d1:
                    st.markdown("### Compliant Areas")
                    st.markdown('<div class="result-box">', unsafe_allow_html=True)
                    st.markdown(compliant if compliant else "- No compliant areas identified.")
                    st.markdown("</div>", unsafe_allow_html=True)

                    st.markdown("### Partially Compliant Areas")
                    st.markdown('<div class="result-box">', unsafe_allow_html=True)
                    st.markdown(partially_compliant if partially_compliant else "- No partially compliant areas identified.")
                    st.markdown("</div>", unsafe_allow_html=True)

                with d2:
                    st.markdown("### Non-Compliant Areas")
                    st.markdown('<div class="result-box">', unsafe_allow_html=True)
                    st.markdown(non_compliant if non_compliant else "- No non-compliant areas identified.")
                    st.markdown("</div>", unsafe_allow_html=True)

                    st.markdown("### Recommendations")
                    st.markdown('<div class="result-box">', unsafe_allow_html=True)
                    st.markdown(recommendations if recommendations else "- No recommendations available.")
                    st.markdown("</div>", unsafe_allow_html=True)

                st.markdown("## Full Compliance Report")
                st.markdown('<div class="result-box">', unsafe_allow_html=True)
                st.markdown(analysis_text)
                st.markdown("</div>", unsafe_allow_html=True)

                tab1, tab2, tab3 = st.tabs(["Retrieved Evidence", "Model Context", "Processing Details"])

                with tab1:
                    st.markdown("### Retrieved Internal Policy Evidence")
                    if retrieved_chunks:
                        for i, chunk in enumerate(retrieved_chunks, start=1):
                            page_number = chunk.get("page_number", "N/A")
                            score_value = round(chunk.get("score", 0), 4)
                            with st.expander(f"Chunk {i} | Page {page_number} | Similarity {score_value}"):
                                st.write(chunk.get("text", ""))
                    else:
                        st.info("No retrieved evidence available.")

                with tab2:
                    st.markdown("### Internal Context Sent to the Model")
                    st.text_area(
                        "Context",
                        value=result["internal_context"],
                        height=300
                    )

                with tab3:
                    st.markdown("### Processing Details")
                    p1, p2 = st.columns(2)

                    with p1:
                        st.markdown("#### Mother Policy")
                        st.write("Pages:", len(processed["mother_policy"]["pages"]))
                        st.write("Chunks:", len(processed["mother_policy"]["chunks"]))

                    with p2:
                        st.markdown("#### Internal Policy")
                        st.write("Pages:", len(processed["internal_policy"]["pages"]))
                        st.write("Chunks:", len(processed["internal_policy"]["chunks"]))

                st.success("Compliance dashboard generated successfully.")

            except Exception as e:
                st.error(f"An error occurred: {str(e)}")