# -*- coding: utf-8 -*-
"""agent_utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KfV2UYLCWJ_zzivLmthOr32-fdUSVlmJ
"""

from .pdfreader_utils import process_policies
from .rag_utils import build_chunk_index, retrieve_top_chunks, build_rag_context
from .llm_utils import call_llm_text

SYSTEM_PROMPT = """
You are an Internal Audit Compliance Assistant.

Your task is to compare the INTERNAL POLICY against the MOTHER POLICY
and identify areas of compliance and non-compliance.

You must:
1. Identify the main requirements in the mother policy.
2. Check whether each requirement is addressed in the internal policy.
3. Highlight gaps, weaknesses, or missing controls.
4. Estimate an overall compliance percentage.

Return the result EXACTLY in the following format:

Overall Compliance Score: <percentage>

Summary:
- <brief explanation of overall compliance>

Compliant Areas:
- <list compliant items>

Partially Compliant Areas:
- <list partially compliant items>

Non-Compliant Areas:
- <list missing or weak requirements>

Recommendations:
- <practical recommendations to fix gaps>
""".strip()

def build_compliance_prompt(mother_text, internal_context):
    prompt = f"""
Compare the following policies and assess compliance.

=== MOTHER POLICY ===
{mother_text}

=== RELEVANT INTERNAL POLICY EXCERPTS ===
{internal_context}
""".strip()

    return prompt

def prepare_internal_policy_context(internal_chunks, query, top_k=5, max_chars=12000):
    indexed_chunks = build_chunk_index(internal_chunks)

    retrieved_chunks = retrieve_top_chunks(
        query=query,
        indexed_chunks=indexed_chunks,
        top_k=top_k
    )

    internal_context = build_rag_context(
        retrieved_chunks=retrieved_chunks,
        max_chars=max_chars
    )

    return internal_context, retrieved_chunks

def run_compliance_agent(
    mother_file,
    internal_file,
    query="data retention, incident response, compliance monitoring, governance roles, access control, policy requirements",
    top_k=5,
    mother_max_chars=12000,
    internal_max_chars=12000,
    model=None
):
    processed = process_policies(mother_file, internal_file)

    mother_text = processed["mother_policy"]["full_text"][:mother_max_chars].strip()
    internal_chunks = processed["internal_policy"]["chunks"]

    internal_context, retrieved_chunks = prepare_internal_policy_context(
        internal_chunks=internal_chunks,
        query=query,
        top_k=top_k,
        max_chars=internal_max_chars
    )

    user_prompt = build_compliance_prompt(
        mother_text=mother_text,
        internal_context=internal_context
    )

    analysis_result = call_llm_text(
        system_prompt=SYSTEM_PROMPT,
        user_prompt=user_prompt,
        model=model
    )

    return {
        "analysis_result": analysis_result,
        "mother_policy_text": mother_text,
        "internal_context": internal_context,
        "retrieved_chunks": retrieved_chunks,
        "processed_data": processed
    }