# -*- coding: utf-8 -*-
"""llm_utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x7nnA6gomX1Q-x0c9wwWYGiniCfW6X10
"""

import os
import json
import re
from openai import OpenAI

DEFAULT_CHAT_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
DEFAULT_EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", "text-embedding-3-small")

def get_client():
    """
    Create and return an OpenAI client using the API key
    stored in environment variables.
    """
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise ValueError("OPENAI_API_KEY is missing.")
    return OpenAI(api_key=api_key)

def extract_json_from_text(text: str):
    """
    Extract JSON content from a model response.
    Supports:
    1. Raw JSON
    2. JSON inside ```json fenced blocks
    3. JSON embedded in plain text
    """
    text = text.strip()

    try:
        return json.loads(text)
    except Exception:
        pass

    fenced = re.search(r"```json\s*(\{.*?\}|\[.*?\])\s*```", text, re.S)
    if fenced:
        return json.loads(fenced.group(1))

    raw = re.search(r"(\{.*\}|\[.*\])", text, re.S)
    if raw:
        return json.loads(raw.group(1))

    raise ValueError("Could not parse JSON from model response.")

def call_llm_text(
    system_prompt: str,
    user_prompt: str,
    model: str = None,
    temperature: float = 0.2
):
    """
    Send text prompts to the model and return plain text output.
    """
    client = get_client()
    model = model or DEFAULT_CHAT_MODEL

    response = client.chat.completions.create(
        model=model,
        temperature=temperature,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ]
    )

    return response.choices[0].message.content.strip()

def call_llm_json(
    system_prompt: str,
    user_prompt: str,
    model: str = None,
    temperature: float = 0.1
):
    """
    Send prompts to the model and parse the response as JSON.
    """
    text = call_llm_text(
        system_prompt=system_prompt,
        user_prompt=user_prompt,
        model=model,
        temperature=temperature
    )
    return extract_json_from_text(text)