# -*- coding: utf-8 -*-
"""rag_utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-cm9463YCKqnpjQXHehrksc_rVtEmCcL
"""

import numpy as np
from .llm_utils import get_client, DEFAULT_EMBEDDING_MODEL

def _normalize(vector):
    """
    Normalize an embedding vector for cosine similarity.
    """
    vector = np.array(vector, dtype=np.float32)
    norm = np.linalg.norm(vector)

    if norm == 0:
        return vector

    return vector / norm

def embed_texts(texts, model=None, batch_size=32):
    """
    Generate embeddings for a list of texts using the embedding model.
    """
    client = get_client()
    model = model or DEFAULT_EMBEDDING_MODEL

    all_embeddings = []

    for i in range(0, len(texts), batch_size):
        batch = texts[i:i + batch_size]

        response = client.embeddings.create(
            model=model,
            input=batch
        )

        batch_embeddings = [item.embedding for item in response.data]
        all_embeddings.extend(batch_embeddings)

    return all_embeddings

def build_chunk_index(chunks, embedding_model=None):
    """
    Build an indexed version of chunks by attaching normalized embeddings
    to each chunk.
    """
    if not chunks:
        return []

    texts = [chunk["text"] for chunk in chunks]
    embeddings = embed_texts(texts, model=embedding_model)

    indexed_chunks = []

    for chunk, embedding in zip(chunks, embeddings):
        record = dict(chunk)
        record["embedding"] = _normalize(embedding).tolist()
        indexed_chunks.append(record)

    return indexed_chunks

def retrieve_top_chunks(query, indexed_chunks, top_k=5, embedding_model=None):
    """
    Retrieve the most relevant chunks for a given query using cosine similarity.
    """
    if not indexed_chunks:
        return []

    query_embedding = embed_texts([query], model=embedding_model)[0]
    query_embedding = _normalize(query_embedding)

    scored_chunks = []

    for chunk in indexed_chunks:
        chunk_embedding = np.array(chunk["embedding"], dtype=np.float32)
        score = float(np.dot(query_embedding, chunk_embedding))

        item = dict(chunk)
        item["score"] = score
        scored_chunks.append(item)

    scored_chunks.sort(key=lambda x: x["score"], reverse=True)

    return scored_chunks[:top_k]

def build_rag_context(retrieved_chunks, max_chars=12000):
    """
    Build a readable context string from retrieved chunks.
    """
    context_parts = []
    total_chars = 0

    for chunk in retrieved_chunks:
        chunk_text = chunk["text"].strip()
        page_number = chunk.get("page_number", "N/A")
        score = round(chunk.get("score", 0), 4)

        formatted_chunk = (
            f"[Page {page_number} | Score: {score}]\n"
            f"{chunk_text}"
        )

        if total_chars + len(formatted_chunk) > max_chars:
            break

        context_parts.append(formatted_chunk)
        total_chars += len(formatted_chunk)

    return "\n\n".join(context_parts)